/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/src/lib/groq/sanity-schema.json
export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: "Twitter" | "Youtube" | "Email" | "Github" | "Linkedin";
  link: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ProjectImage = {
  _id: string;
  _type: "projectImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  alt: string;
  caption: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type ProjectImageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectImage";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  featuredDescription: string;
  slug: Slug;
  featuredImage: ImageInfo;
  description: Description;
  projectImages?: Array<
    {
      _key: string;
    } & ProjectImageReference
  >;
};

export type Description = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ImageInfo = {
  _type: "imageInfo";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type BlogReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blog";
};

export type BlogBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<
        | {
            reference?: BlogReference;
            _type: "internalLink";
            _key: string;
          }
        | {
            href?: string;
            blank?: boolean;
            _type: "link";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
>;

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string;
  body: BlogBody;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProjectReference
  | Homepage
  | Contact
  | SanityImageAssetReference
  | ProjectImage
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectImageReference
  | Project
  | Description
  | ImageInfo
  | Slug
  | BlogReference
  | BlogBody
  | Blog
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/groq/getBlogBySlug.ts
// Variable: getBlogBySlug
// Query: *[_type == "blog" && slug.current == $slug] {  title,  excerpt,  slug,  publishedAt,  body[]{    ...,    _type == "image" => {      "asset": @.asset->{        ...      }    },    markDefs[]{      ...,      _type == "internalLink" => {        "slug": @.reference->slug      }    }  }}[0]
export type GetBlogBySlugResult = {
  title: string;
  excerpt: string;
  slug: Slug;
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet";
        markDefs: Array<
          | {
              reference?: BlogReference;
              _type: "internalLink";
              _key: string;
              slug: Slug | null;
            }
          | {
              href?: string;
              blank?: boolean;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash: string;
          extension: string;
          mimeType: string;
          size: number;
          assetId: string;
          uploadId?: string;
          path: string;
          url: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
        markDefs: null;
      }
  >;
} | null;

// Source: ../web/src/lib/groq/getBlogSlugs.ts
// Variable: getBlogSlugs
// Query: *[_type == "blog" && defined(slug.current)] {  "slug": slug.current,  publishedAt} | order(publishedAt desc)
export type GetBlogSlugsResult = Array<{
  slug: string;
  publishedAt: string;
}>;

// Source: ../web/src/lib/groq/getBlogs.ts
// Variable: getBlogs
// Query: *[_type == "blog"] {  title,  excerpt,  slug,  publishedAt,  "readingTime": round(length(pt::text(body)) / 5 / 200 )} | order(publishedAt desc)
export type GetBlogsResult = Array<{
  title: string;
  excerpt: string;
  slug: Slug;
  publishedAt: string;
  readingTime: number;
}>;

// Source: ../web/src/lib/groq/getContacts.ts
// Variable: getContacts
// Query: *[_type == "contact" && !(_id in path("drafts.**"))] {  link,  title} | order(title asc)
export type GetContactsResult = Array<{
  link: string;
  title: "Email" | "Github" | "Linkedin" | "Twitter" | "Youtube";
}>;

// Source: ../web/src/lib/groq/getProjectBySlug.ts
// Variable: getProjectBySlug
// Query: *[  _type == "project"  && slug.current == $slug  && !(_id in path("drafts.**"))  && _id in *[_type == "homepage"][0].projects[]._ref] {  _id,  title,  description,  featuredDescription,  featuredImage {    asset -> {      url,    }  },  slug,  "projectImages": projectImages[]-> {    _id,    alt,    caption,    image {      asset->{        ...,      }    }  }}[0]
export type GetProjectBySlugResult = {
  _id: string;
  title: string;
  description: Description;
  featuredDescription: string;
  featuredImage: {
    asset: {
      url: string;
    } | null;
  };
  slug: Slug;
  projectImages: Array<{
    _id: string;
    alt: string;
    caption: string;
    image: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
    };
  }> | null;
} | null;

// Source: ../web/src/lib/groq/getProjects.ts
// Variable: getProjects
// Query: *[_type == "homepage"][0].projects[]-> {  _id,  featuredImage {    asset -> {      ...,    }  },  featuredDescription,  title,  slug}
export type GetProjectsResult = Array<{
  _id: string;
  featuredImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  };
  featuredDescription: string;
  title: string;
  slug: Slug;
}> | null;

// Source: ../web/src/lib/groq/getProjectsSlugs.ts
// Variable: getProjectSlugs
// Query: *[_type == "homepage"][0].projects[]-> {  slug}
export type GetProjectSlugsResult = Array<{
  slug: Slug;
}> | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "blog" && slug.current == $slug] {\n  title,\n  excerpt,\n  slug,\n  publishedAt,\n  body[]{\n    ...,\n    _type == "image" => {\n      "asset": @.asset->{\n        ...\n      }\n    },\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        "slug": @.reference->slug\n      }\n    }\n  }\n}[0]': GetBlogBySlugResult;
    '*[_type == "blog" && defined(slug.current)] {\n  "slug": slug.current,\n  publishedAt\n} | order(publishedAt desc)': GetBlogSlugsResult;
    '*[_type == "blog"] {\n  title,\n  excerpt,\n  slug,\n  publishedAt,\n  "readingTime": round(length(pt::text(body)) / 5 / 200 )\n} | order(publishedAt desc)': GetBlogsResult;
    '*[_type == "contact" && !(_id in path("drafts.**"))] {\n  link,\n  title\n} | order(title asc)': GetContactsResult;
    '*[\n  _type == "project"\n  && slug.current == $slug\n  && !(_id in path("drafts.**"))\n  && _id in *[_type == "homepage"][0].projects[]._ref\n] {\n  _id,\n  title,\n  description,\n  featuredDescription,\n  featuredImage {\n    asset -> {\n      url,\n    }\n  },\n  slug,\n  "projectImages": projectImages[]-> {\n    _id,\n    alt,\n    caption,\n    image {\n      asset->{\n        ...,\n      }\n    }\n  }\n}[0]': GetProjectBySlugResult;
    '*[_type == "homepage"][0].projects[]-> {\n  _id,\n  featuredImage {\n    asset -> {\n      ...,\n    }\n  },\n  featuredDescription,\n  title,\n  slug\n}': GetProjectsResult;
    '*[_type == "homepage"][0].projects[]-> {\n  slug\n}': GetProjectSlugsResult;
  }
}
